// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIA.Infrastructure;

#nullable disable

namespace ProyectoIA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923022822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProyectoIA.Domain.BitacoraCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("GestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GestionId");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("ProyectoIA.Domain.Ceco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CECO-001",
                            Nombre = "Centro de Costo Principal"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CECO-002",
                            Nombre = "Centro de Costo Secundario"
                        });
                });

            modelBuilder.Entity("ProyectoIA.Domain.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dependencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Operaciones"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Finanzas"
                        });
                });

            modelBuilder.Entity("ProyectoIA.Domain.Gestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CecoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCambioEstado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CecoId");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("Gestiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CecoId = 1,
                            DependenciaId = 1,
                            Detalle = "Automatizar el proceso mensual de conciliación para reducir el trabajo manual.",
                            Estado = 1,
                            Fecha = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCambioEstado = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Objetivo = "Automatizar conciliación bancaria",
                            ReferenciaIngreso = "MEMO-001",
                            SolicitanteId = 3,
                            TipoSolicitudId = 1
                        },
                        new
                        {
                            Id = 2,
                            CecoId = 2,
                            DependenciaId = 2,
                            Detalle = "Digitalizar el flujo de aprobación de órdenes de compra.",
                            Estado = 2,
                            Fecha = new DateTime(2026, 9, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaAsignacion = new DateTime(2026, 9, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCambioEstado = new DateTime(2026, 9, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Objetivo = "Flujo de aprobación de compras",
                            ReferenciaIngreso = "MEMO-002",
                            SolicitanteId = 3,
                            TecnicoAsignadoId = 2,
                            TipoSolicitudId = 2
                        });
                });

            modelBuilder.Entity("ProyectoIA.Domain.NotaGestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPublica")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("GestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GestionId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ProyectoIA.Domain.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "RPA"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "BPM"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Power Platform"
                        });
                });

            modelBuilder.Entity("ProyectoIA.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@proyectoia.com",
                            Nombre = "Administrador",
                            PasswordHash = "3EB3FE66B31E3B4D10FA70B5CAD49C7112294AF6AE4E476A1C405155D45AA121",
                            Rol = 3
                        },
                        new
                        {
                            Id = 2,
                            Correo = "tecnico@proyectoia.com",
                            Nombre = "Técnico",
                            PasswordHash = "91C8C18A270E60459C62B1491F4314923E660E8B2030A33BD7F135BBDE990C30",
                            Rol = 2
                        },
                        new
                        {
                            Id = 3,
                            Correo = "cliente@proyectoia.com",
                            Nombre = "Cliente",
                            PasswordHash = "519F24A823B10612516C33F438F12967A179AB77D6E7D2AF68F3B9F2631345A7",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("ProyectoIA.Domain.BitacoraCambio", b =>
                {
                    b.HasOne("ProyectoIA.Domain.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoIA.Domain.Gestion", "Gestion")
                        .WithMany("Bitacora")
                        .HasForeignKey("GestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Gestion");
                });

            modelBuilder.Entity("ProyectoIA.Domain.Gestion", b =>
                {
                    b.HasOne("ProyectoIA.Domain.Ceco", "Ceco")
                        .WithMany()
                        .HasForeignKey("CecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIA.Domain.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIA.Domain.Usuario", "Solicitante")
                        .WithMany("GestionesSolicitadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIA.Domain.Usuario", "TecnicoAsignado")
                        .WithMany("GestionesAsignadas")
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIA.Domain.TipoSolicitud", "TipoSolicitud")
                        .WithMany()
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceco");

                    b.Navigation("Dependencia");

                    b.Navigation("Solicitante");

                    b.Navigation("TecnicoAsignado");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("ProyectoIA.Domain.NotaGestion", b =>
                {
                    b.HasOne("ProyectoIA.Domain.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoIA.Domain.Gestion", "Gestion")
                        .WithMany("Notas")
                        .HasForeignKey("GestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Gestion");
                });

            modelBuilder.Entity("ProyectoIA.Domain.Gestion", b =>
                {
                    b.Navigation("Bitacora");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("ProyectoIA.Domain.Usuario", b =>
                {
                    b.Navigation("GestionesAsignadas");

                    b.Navigation("GestionesSolicitadas");
                });
#pragma warning restore 612, 618
        }
    }
}
